// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.5
package org.example.weather;

public final class Weather {
  private Weather() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weather_PlaceMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weather_PlaceMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weather_WeatherMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weather_WeatherMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rweather.proto\022\007weather\"\034\n\014PlaceMessage" +
      "\022\014\n\004city\030\001 \001(\t\"D\n\016WeatherMessage\022\014\n\004city" +
      "\030\001 \001(\t\022\017\n\007weather\030\002 \001(\t\022\023\n\013temperature\030\003" +
      " \001(\0052P\n\016WeatherService\022>\n\nGetWeather\022\025.w" +
      "eather.PlaceMessage\032\027.weather.WeatherMes" +
      "sage\"\000B\027\n\023org.example.weatherP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_weather_PlaceMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_weather_PlaceMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weather_PlaceMessage_descriptor,
        new java.lang.String[] { "City", });
    internal_static_weather_WeatherMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_weather_WeatherMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weather_WeatherMessage_descriptor,
        new java.lang.String[] { "City", "Weather", "Temperature", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
