// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

// Protobuf Java Version: 3.25.5
package org.example.weather;

public interface WeatherMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:weather.WeatherMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string city = 1;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 1;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string weather = 2;</code>
   * @return The weather.
   */
  java.lang.String getWeather();
  /**
   * <code>string weather = 2;</code>
   * @return The bytes for weather.
   */
  com.google.protobuf.ByteString
      getWeatherBytes();

  /**
   * <code>int32 temperature = 3;</code>
   * @return The temperature.
   */
  int getTemperature();
}
